name: Build and publish container images
on: [push, pull_request]
jobs:
  build_publish:
    name: Build/publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform: [amd64, arm64]
        tag:
          - centos-7.9
          - centos-8.4
          - fedora-35
          - opensuse-15.3
          - rockylinux-8.5
          - ubuntu-20.04
          - redhat-ubi-8.6
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.tag }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.tag }}

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert and store repository owner in lowercase
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo DOCKERFILE=${{ matrix.tag }}/Dockerfile >> $GITHUB_ENV

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }}-${{ matrix.platform }}
          file: ${{ env.DOCKERFILE }}
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  docker_manifest:
    name: Docker manifest
    needs: build_publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        tag:
          - centos-7.9
          - centos-8.4
          - fedora-35
          - opensuse-15.3
          - rockylinux-8.5
          - ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert and store repository owner in lowercase
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Run docker manifest
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          docker manifest create \
            ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }} \
            --amend ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }}-amd64 \
            --amend ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }}-arm64

      - name: Push manifest
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: docker manifest push ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.tag }}
